// Re-export types from other files to maintain backward compatibility
export type {
  Product,
  Category,
  ProfitLevel,
  ProfitLevelConfig,
  ProfitAnalytics,
  DailySalesSummary,
  ValidatedProduct,
  ValidatedCategory,
  ValidatedProducts,
  ValidatedCategories,
  ValidatedStore,
} from "./database";

export type {
  ProductCardProps,
  ProductGridProps,
  SearchBarProps,
  KeypadProps,
  SuccessScreenProps,
  ProductGridSkeletonProps,
  QuickAccessSectionProps,
  ButtonVariant,
  KeypadButtonProps,
  CartProduct,
  EventHandlerProps,
  MainLayoutProps,
  LeftPanelProps,
  RightPanelProps,
  ProductManagerProps,
  CartManagerProps,
  ProductGridHeaderProps,
  ProductGridContentProps,
  ErrorDisplayProps,
  DailyMetricsCardProps,
  SkeletonItemProps,
} from "./components";
